### ISSUE TITLE
4) Create a basic version of the GUI in Scene Builder and bind it to the project

### ISSUE THREAD

**Issue by Hyujinx** [William-Carbonneau/wave-simulation#11]
# Description
Create scenes in Scene Builder as it is much faster to create and to make changes compared to writing the UI manually.

## Subtasks

- [ ] 4A) Creating the main scene in Scene Builder

- [ ] 4B) Building the Scene in NetBeans

- [ ] 4C) Migrate simulation to fxml project
