### ISSUE TITLE
6) Implement rendering in the simulation

### ISSUE THREAD

**Issue by Hyujinx** [William-Carbonneau/wave-simulation#12]
# Description
Implementing the rendering feature to save the simulation to a file or set of ordered frame files.

## Subtasks

- [ ] 6A) Parsing the simulation into a file 

- [ ] 6B) Implement the View Render tab in scene builder

- [ ] 6C) Viewing the render in the view render tab

- [ ] 6D) Implement the Max Frames feature

- [ ] 6E) Implement Popup Dialog for Finished Simulation

- [ ] 6EA) Create fxml for “render finished” popup

- [ ] 6F) “Change render folder” button
