### ISSUE TITLE
2) Implementing a basic version of the simulation

### ISSUE THREAD

**Issue by Hyujinx** [William-Carbonneau/wave-simulation#8]
# Description
Before anything else can be done, first, the simulation must function in a basic form. This means a basic grid on the screen.

## Subtasks

- [ ] 2A)Implementing the back-end array

- [x] 2B) Implementing a grid and a stage

- [ ] 2C) Drive the grid pixels with the array
